"""added album status

Revision ID: a337b3f88bf1
Revises: bd8d699fa622
Create Date: 2025-09-16 20:08:54.362324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a337b3f88bf1'
down_revision: Union[str, Sequence[str], None] = 'bd8d699fa622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'album_statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.Column('time_stamp', sa.DateTime(), nullable=False),
        sa.Column(
            'status', sa.Enum('ADDED', 'MODIFIED', name='status'), nullable=False
        ),
        sa.Column(
            'success',
            sa.Enum('SUCCESS', 'WARNING', 'ERROR', name='success'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_album_statuses_album_id'), 'album_statuses', ['album_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_statuses_album_id'), table_name='album_statuses')
    op.drop_table('album_statuses')

    status_enum = sa.Enum('ADDED', 'MODIFIED', name='status')
    success_enum = sa.Enum('SUCCESS', 'WARNING', 'ERROR', name='success')
    status_enum.drop(op.get_bind())
    success_enum.drop(op.get_bind())
    # ### end Alembic commands ###
