name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    env:
      ASYNC_DB_URL: postgresql+asyncpg://user:pass@localhost:5432/testdb
      SYNC_DB_URL: postgresql+psycopg2://user:pass@localhost:5432/testdb

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --with dev --with db --without ML

      - name: Migrate DB
        run: |
          poetry run alembic upgrade head

      - name: Run Ruff formatter check
        run: |
          poetry run ruff format . --check

      - name: Run Ruff linter check
        run: |
          poetry run ruff check .

      - name: Run Mypy check
        run: |
          poetry run mypy .

      - name: Run tests and generate coverage report
        run: |
          poetry run pytest --cov-report=lcov tests/

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
